
const jsonAtividadeEmpresas = {
  "profissoesEmpresas": [
    "Advogado",
    "Agente de Viagens",
    "Agrônomo",
    "Alfaiate",
    "Almoxarife",
    "Analista de Dados",
    "Analista de Marketing",
    "Analista de Sistemas",
    "Arquiteto",
    "Artista Plástico",
    "Assistente Administrativo",
    "Assistente Social",
    "Atendente",
    "Auditor",
    "Auxiliar de Enfermagem",
    "Babá",
    "Barman",
    "Biomédico",
    "Bibliotecário",
    "Biólogo",
    "Cabeleireiro",
    "Caixa",
    "Carpinteiro",
    "Chef de Cozinha",
    "Cientista da Computação",
    "Comissário de Bordo",
    "Consultor",
    "Contador",
    "Coordenador de Projetos",
    "Costureira",
    "Cuidador de Idosos",
    "Designer Gráfico",
    "Designer de Interiores",
    "Desenvolvedor Front-end",
    "Desenvolvedor Back-end",
    "Desenvolvedor Web",
    "Diarista",
    "Economista",
    "Educador Físico",
    "Eletricista",
    "Encanador",
    "Enfermeiro",
    "Engenheiro Civil",
    "Engenheiro de Produção",
    "Engenheiro de Software",
    "Engenheiro Mecânico",
    "Escritor",
    "Esteticista",
    "Farmacêutico",
    "Fisioterapeuta",
    "Fotógrafo",
    "Garçom",
    "Gerente Comercial",
    "Gerente de Projetos",
    "Gerente Financeiro",
    "Gestor Ambiental",
    "Gestor de Recursos Humanos",
    "Guia de Turismo",
    "Instrutor de Autoescola",
    "Jardineiro",
    "Jornalista",
    "Lavador de Carros",
    "Mecânico",
    "Médico",
    "Motoboy",
    "Motorista",
    "Nutricionista",
    "Operador de Caixa",
    "Operador de Máquinas",
    "Padeiro",
    "Pedagogo",
    "Pedreiro",
    "Personal Trainer",
    "Pescador",
    "Pintor",
    "Porteiro",
    "Professor",
    "Programador",
    "Promotor de Vendas",
    "Psicólogo",
    "Publicitário",
    "Recepcionista",
    "Redator",
    "Representante Comercial",
    "Secretária",
    "Segurança",
    "Servente de Obras",
    "Serviços Gerais",
    "Soldador",
    "Supervisor de Produção",
    "Técnico Agrícola",
    "Técnico de Enfermagem",
    "Técnico de Informática",
    "Técnico Eletrônico",
    "Técnico em Mecatrônica",
    "Técnico em Segurança do Trabalho",
    "Taxista",
    "Tradutor",
    "Vendedor",
    "Veterinário",
    "Web Designer",
    "Zootecnista"
  ]
};

const selectElement = document.getElementById("profissoesSelectEmpresa");

jsonAtividadeEmpresas.profissoesEmpresas.forEach((profissaoEmpresas, index) => {
  const option = document.createElement("option");
  option.value = index + 1;
  option.textContent = profissaoEmpresas;
  selectElement.appendChild(option);
});

